article/urls.py
from django.contrib import admin
from django.urls import path
from . import views # şuanki klasördekki viewsi al
app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addarticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment")
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('about/',views.about, name="about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views # şuanki klasördekki viewsi al
app_name = "user"

urlpatterns = [
    path('',views.userIndex, name = "userIndex"),
    path('register/',views.register, name = "register"),
    path('login/',views.loginUser, name = "login"),
    path('logout/',views.logoutUser, name = "logout")

]

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">YbBlog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Anasayfa <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">Hakkımızda</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:articles' %}" tabindex="-1">Makaleler</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:logout' %}">Çıkış yap</a>
            </li>
          {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:register' %}">Kayıt ol</a>
            </li>
            <li class="nav-item">
                  <a class="nav-link" href="{% url 'user:login' %}">Giriş yap</a>
            </li>
          {% endif %}          
      </ul>
    </div>
  </nav>

templates/includes/posttemplate.html
<div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">
  
          <!-- Title -->
          <h1 class="mt-4">Post Title</h1>
  
          <!-- Author -->
          <p class="lead">
            by
            <a href="#">Start Bootstrap</a>
          </p>
  
          <hr>
  
          <!-- Date/Time -->
          <p>Posted on January 1, 2019 at 12:00 PM</p>
  
          <hr>
  
          <!-- Preview Image -->
          <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">
  
          <hr>
  
          <!-- Post Content -->
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>
  
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>
  
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
  
          <blockquote class="blockquote">
            <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
            <footer class="blockquote-footer">Someone famous in
              <cite title="Source Title">Source Title</cite>
            </footer>
          </blockquote>
  
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>
  
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>
  
          <hr>
  
          
          
  
          
          
  
          
          
  
        </div>
  
        
        
  
      </div>