article/urls.py
from django.contrib import admin
from django.urls import path
from . import views # şuanki klasördekki viewsi al
app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addarticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment")
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('about/',views.about, name="about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Yazar") # o user silinirse her şeyi gider :D
    title = models.CharField(max_length = 50,verbose_name = "Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturma tarihi") # o anki tarihi alır
    article_image = models.FileField(blank=True, null=True, verbose_name="Makaleye fotoğraf ekleyin")
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-created_date']
class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE, verbose_name = "Makale",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "isim")
    comment_content = models.CharField(max_length = 200,verbose_name = "Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-comment_date']
    def __str__(self):
        return self.comment_content

article/forms.py
from django import forms
from .models import Article
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from django.contrib.auth.decorators import login_required
from .forms import  ArticleForm
from .models import Article, Comment
from django.contrib import messages
from django.utils.html import strip_tags
def index(request): #request gerekli ilk parametre olarak
    #return HttpResponse("anasayfa")
    context = {
        "numbers": [1,2,3,4,5,6]
    }
    #return render(request,"index.html",{"number":7})
    return render(request,"index.html",context)
def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})
def about(request):
    return render(request,'about.html')
@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }
    return render(request,'dashboard.html',context)
@login_required(login_url="user:login")
def addarticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.add_message(request, messages.SUCCESS,"Makale başarıyla oluşturuldu")
        return redirect("index")
    context = {
        "form":form
    }
    return render(request,"addarticle.html",context)

def detail(request,id):
    #article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article,id =id)
    comments = article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})
@login_required(login_url="user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance = article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.add_message(request, messages.SUCCESS,"Makale başarıyla güncellendi")
        return redirect("index")
    
    return render(request, "update.html",{"form":form})
@login_required(login_url="user:login")
def deleteArticle(request, id):
    article = get_object_or_404(Article,id = id)
    article.delete()
    messages.add_message(request, messages.SUCCESS,"Makale başarıyla silindi")
    return redirect("article:dashboard")
        
def addComment(request,id):
    article = get_object_or_404(Article,id = id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        newComment = Comment(comment_author = comment_author,comment_content=comment_content)
        newComment.article = article
        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))

templates/about.html
{% extends "layout.html" %}

{% block body %}

<h3>Hakkımızda</h3>
<hr> 
<p>
    Merhaba ziyaretçi, ben Ümit DEMİR. Burda yaptığım şey aslında python'ın django framework'ü ile bir web sitesi tasarlamak<br>
    Bunu neden mi istiyorum? Zaten pythona bi hayranlığım var. Çünkü tek bir dil öğrenerek onun alt frameworkleri sayesinde farklı dallarda uygulama geliştirebiliyoruz
</p>

{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Makale ekle</h3>
            <hr>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.media}}
                {{form|crispy}}
                <button type="submit" class="btn btn-danger">Makaleyi oluştur</button>
             </form>
        </div>
    </div>

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}
<div class="row">
        <div class="col-lg-8">
<h3>Makaleler</h3>
<form>
    {% csrf_token %}
    <input type="text" name="keyword" class="input input-md-3" placeholder="ara">
    <button type="submit" class="btn btn-danger">Ara</button>
</form>
<hr>
{% if articles %}
{% for article in articles  %}


        <!-- Post Content Column -->
        
          
          <!-- Title -->
          <a href="{% url 'article:detail' article.id %}"><h1 class="mt-4">{{article.title}}</h1></a>
  
          <!-- Author -->
          <p class="lead">
            by
           {{article.author.username}}
          </p>
  
          <hr>
  
          <!-- Date/Time -->
          <p>{{article.created_date}}</p>
  
          <hr>
          {% if article.article_image %}
            <img src="{{article.article_image.url}}" alt="" class="img-fluid rounded">
          {% else %}
          {% endif %}
          
          <hr>
          <p class="content">{{article.content|safe|truncatewords:30}}</p>
        <a style = "float:right;"href="/articles/article/{{article.id}}" class = "btn btn-success">Devamını oku</a>
          <hr>
  
          <br>
          
          <style>
            p.content img{
                max-width: 700px;
            }
          </style>
          
          
  
          
          
  
        </div>
  
        
        
  
      </div>
{% endfor %}
{% else %}
<div class="alert alert-danger">makale bulunamadı</div>
{% endif %}
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
<h3>Kontrol Paneli</h3>
<hr>
<p>
    Hoşgeldiniz, <small>{{request.user.username}}</small>
</p>
<hr>
<a class="btn btn-danger" href="/articles/addarticle">Makale ekle</a>
<hr>
{% if articles %}
    <table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Başlık</th>
            <th scope="col">Yazar</th>
            <th scope="col">Tarih</th>
            <th>Güncelle</th>
            <th>Sil</th>
          </tr>
        </thead>
        <tbody>

          {% for article in articles  %}
            <tr>
                <th scope="row">{{article.id}}</th>
                <td><a href="/articles/article/{{article.id}}">{{article.title}} </a></td>
                <td>{{article.author.username}}</td>
                <td>@{{article.created_date}}</td>
                <td><a href="/articles/update/{{article.id}}" class="btn btn-danger">Güncelle</a></td>
                <td><a href="/articles/delete/{{article.id}}" class="btn btn-danger">Sil</a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
{% else %}
    <div class="alert alert-danger">Henüz bir makaleniz bulunmuyor</div>
{% endif %}

{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% block body %}
<div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">
          
          <!-- Title -->
          <h1 class="mt-4">{{article.title}}</h1>
  
          <!-- Author -->
          <p class="lead">
            by
           {{article.author.username}}
          </p>
  
          <hr>
  
          <!-- Date/Time -->
          <p>{{article.created_date}}</p>
  
          <hr>
          {% if article.article_image %}
            <img src="{{article.article_image.url}}" alt="" class="img-fluid rounded">
          {% else %}
          {% endif %}
          
          <hr>
          <p class="content">{{article.content|safe}}</p>
          <hr>
        
  
          
          <div class="card my-4">
              <h5 class="card-header">Yorum ekle:</h5>
              <div class="card-body">
                <form method="post" action="{% url 'article:comment' article.id %}">
                  {% csrf_token %}
                  <div class="form-group">
                      <label for="exampleFormControlInput1">İsim</label>
                      <input name = "comment_author" type="text" class="form-control" id="exampleFormControlInput1" placeholder="Örn: Murat">
                    </div>
                  <div class="form-group">
                      <label for="exampleFormControlInput1">Yorum:</label>
                    <textarea name = "comment_content" class="form-control" rows="3"></textarea>
                  </div>
                  <button type="submit" class="btn btn-primary">Ekle</button>
                </form>
              </div>
            </div>
            <h4>Yorumlar</h4>
            <hr>
            {% if comments %}
              {% for comment in comments %}
              <div class="media mb-4">
                  <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                  <div class="media-body">
                    <h5 class="mt-0">{{comment.comment_author}}</h5>
                    <small>Tarih: {{comment.comment_date}}</small><br>
                    {{comment.comment_content}}
                   
                  </div>
                </div>
                <hr>
              {% endfor %}
              
            {% else %}
            <div class = "alert alert-danger">Bu makaleye herhangi bir yorum yazılmamış. İlk yorum yapan sen ol</div>
            {% endif %}
          <style>
            p.content img{
                max-width: 700px;
            }
          </style>
          
          
  
          
          
  
        </div>
  
        
        
  
      </div>
{% endblock body %}

templates/index.html
{% extends "layout.html" %}
{% block body %}
    <div class="jumbotron text-center">
        <h3>Yazılım bilgi bloğuna hoş geldiniz</h3>
        <p>Bu blogta geliştiriciler olarak blog yazılarınızı paylaşabilirsiniz ve insanlara yardımcı olabilirsiniz</p>
    </div>
    <p>
      <!----  <ul>
            {% for number in numbers %}
                <li>{{number}}</li>
            {% endfor %}
        </ul>
    -->
    {% if request.user.is_authenticated %}
        giriş yapılmış, {{request.user.username}}
    {% else %}
        giriş yapılmamış
    {% endif %}
    </p>
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css '%}">
    <title>YbBlog</title>
</head>
<body>
    {% include "includes/navbar.html" %}

    <div style = "margin-top: 100px;" class="container">
            {% if messages %}
    
        {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </div>
        {% endfor %}
    
    {% endif %}
        {% block body %}
        
        {% endblock body %}
    </div>

    <script src="{% static 'js/jquery-3.2.1.min.js '%}"></script>
    <script src="{% static 'js/bootstrap.min.js '%}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Giriş yap</h3>
            <hr>
            <form method="POST">
                {% csrf_token %}

                {{form|crispy}}
                <button type="submit" class="btn btn-danger">Giriş yap</button>
             </form>
        </div>
    </div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Kayıt ol</h3>
            <hr>
            <form method="POST">
                {% csrf_token %}

                {{form|crispy}}
                <button type="submit" class="btn btn-danger">Kayıt ol</button>
             </form>
        </div>
    </div>
{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Makaleyi Güncelle</h3>
            <hr>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.media}}
                {{form|crispy}}
                <button type="submit" class="btn btn-danger">Makaleyi güncelle</button>
             </form>
        </div>
    </div>

{% endblock body %}